In [198]:
### Book to cre3ate the route map for the NCAA tournament to apply to the existing map to make some cool visualizations

# Path: NCAA_routes_book.ipynb

### OBJECTIVE create lines with routes of the teams in each regional to the regional site and display them on the NCAA Regional Map
### OUTLINE
#### Get a dataframe of the host address, the three other teams competing in the regional, and the addresses of those three teams

###### Add the school color to each visiting team and create lines between the host and the visiting teams

###### Output the lines as a json object that can be added to my existing NCAA_REG map

In [199]:
import pandas as pd
import numpy as np


# Load the json with all the regional information

df = pd.read_json('data/NCAA_D1/game_info.json')

## Get a list of all of the teams that are in the tournament
teams = df['Team_Name'].unique()

print(teams)

['Southern Miss.' 'Samford' 'Auburn' 'Penn' 'LSU' 'Tulane' 'Oregon St.'
 'Sam Houston' 'Virginia' 'Army West Point' 'East Carolina' 'Oklahoma'
 'Clemson' 'Lipscomb' 'Tennessee' 'Charlotte' 'Campbell' 'NC State'
 'South Carolina' 'Central Conn. St.' 'Duke' 'UNCW' 'Coastal Carolina'
 'Rider' 'Texas' 'Louisiana' 'Miami (FL)' 'Maine' 'Arkansas' 'Santa Clara'
 'TCU' 'Arizona' 'UConn' 'Texas Tech' 'Florida' 'Florida A&M' 'Kentucky'
 'Ball St.' 'West Virginia' 'Indiana' 'Oregon' 'Xavier' 'Vanderbilt'
 'Eastern Ill.' 'Stanford' 'San Jose St.' 'Texas A&M' 'Cal St. Fullerton'
 'DBU' 'Washington' 'Oklahoma St.' 'Oral Roberts' 'Indiana St.'
 'Wright St.' 'Iowa' 'North Carolina' 'Boston College' 'Troy' 'Alabama'
 'Nicholls' 'Maryland' 'Northeastern' 'Wake Forest' 'George Mason']

In [200]:
## Open the json with host team information
host_df = pd.read_json('data/NCAA_D1/regional_tourn_map.json')

In [201]:
## Examine the host_df

# host_df.head()
# host_df.info()

## Create a list of the host teams
## Get rid of the NCAA Final Sites
host_teams = host_df['host_school'].unique()


print(host_teams)

['Clemson' 'Coastal Carolina' 'Auburn' 'Alabama' 'South Carolina'
 'Arkansas' 'Wake Forest' 'Miami (FL)' 'Vanderbilt' 'LSU' 'Indiana St.'
 'Florida' 'Virginia' 'Oklahoma St.' 'Kentucky' 'Stanford'
 'College World Series' 'Division 3 Championship'
 'Division 2 Championship']

In [202]:

## Drop The NCAA Nuetral Sites from the host_df
host_df = host_df[0:16]

host_df.info()
host_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 52 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   park_name                 16 non-null     object
 1   foul                      16 non-null     object
 2   fop                       16 non-null     object
 3   notes                     2 non-null      object
 4   home_plate                16 non-null     object
 5   foul_area_sqft            16 non-null     float64
 6   fop_area_sqft             16 non-null     float64
 7   field_area_sqft           16 non-null     float64
 8   foul_area_per             16 non-null     float64
 9   fair_to_foul              16 non-null     float64
 10  distances                 16 non-null     object
 11  max_distance              16 non-null     float64
 12  min_distance              16 non-null     float64
 13  avg_distance              16 non-null     float64
 14  median_distance           16 non-null     float64
 15  corner_sharpness          16 non-null     float64
 16  max_distance_rank         16 non-null     int64
 17  min_distance_rank         16 non-null     int64
 18  avg_distance_rank         16 non-null     int64
 19  median_distance_rank      16 non-null     int64
 20  field_area_rank           16 non-null     int64
 21  foul_area_rank            16 non-null     int64
 22  fop_area_per_rank         16 non-null     int64
 23  ratio_rank                16 non-null     int64
 24  fop_centroid              16 non-null     object
 25  field_orientation         16 non-null     float64
 26  field_cardinal_direction  16 non-null     object
 27  score                     16 non-null     float64
 28  plotted?                  16 non-null     object
 29  host_school               16 non-null     object
 30  nickname                  16 non-null     object
 31  filename                  16 non-null     object
 32  display_name              16 non-null     object
 33  display_name2             8 non-null      object
 34  color1                    16 non-null     object
 35  color2                    16 non-null     object
 36  color3                    3 non-null      object
 37  found_date                16 non-null     int64
 38  capacity                  16 non-null     object
 39  former_names              12 non-null     object
 40  renovation                11 non-null     object
 41  st_address                15 non-null     object
 42  coords_string1            14 non-null     object
 43  surface                   16 non-null     object
 44  description               15 non-null     object
 45  altitude                  16 non-null     float64
 46  city                      16 non-null     object
 47  state                     16 non-null     object
 48  hr_friendliness           16 non-null     float64
 49  old_school_friendliness   16 non-null     float64
 50  uniqueness_score          16 non-null     float64
 51  file_path                 16 non-null     object
dtypes: float64(16), int64(9), object(27)
memory usage: 6.6+ KB

,park_name,foul,fop,notes,home_plate,foul_area_sqft,fop_area_sqft,field_area_sqft,foul_area_per,fair_to_foul,...,coords_string1,surface,description,altitude,city,state,hr_friendliness,old_school_friendliness,uniqueness_score,file_path
0,Clemson - Doug Kingsmore Stadium,"[[-82.8491983, 34.6791933], [-82.848627, 34.67...","[[-82.8491983, 34.6791933], [-82.8500928, 34.6...",None,"[-82.8491983, 34.6791933]",23613.323755,98047.704889,121661.028644,0.194091,4.152220,...,None,Natural Grass,None,192.230179,Clemson,South Carolina,1.302414,-0.506885,3.303366,data/NCAA_D1/assests/graphs/plot_0.png
1,Coastal Carolina - college,"[[-79.0154049, 33.7935777], [-79.014391, 33.79...","[[-79.0154049, 33.7935777], [-79.015185, 33.79...",None,"[-79.0154049, 33.7935777]",24333.208254,97282.766200,121615.974454,0.200082,3.997942,...,"33.7935°N, 79.0152°W",Natural Grass,"Springs Brooks Stadium, formerly known as Char...",13.008470,Conway,South Carolina,0.529683,0.508495,2.940372,data/NCAA_D1/assests/graphs/plot_1.png
2,Auburn - Plainsman Park,"[[-85.4899848, 32.6000522], [-85.4889635, 32.6...","[[-85.4899848, 32.6000522], [-85.4900418, 32.5...",None,"[-85.4899848, 32.6000522]",21057.394957,99739.053681,120796.448638,0.174321,4.736533,...,32.5998°N 85.4897°W,Natural Grass/Artificial Turf,"Plainsman Park, officially Samford Stadium – H...",193.814285,Auburn,Alabama,0.793680,0.227365,2.512686,data/NCAA_D1/assests/graphs/plot_2.png
3,Alabama - Sewell–Thomas Stadium,"[[-87.5387466, 33.2052609], [-87.5378045, 33.2...","[[-87.5387466, 33.2052609], [-87.5392033, 33.2...",None,"[-87.5387466, 33.2052609]",25771.940467,99800.415822,125572.356290,0.205236,3.872445,...,33°12′19″N 87°32′19″W,Natural Grass,"Sewell–Thomas Stadium, often referred to as \T...",65.636711,Tuscaloosa,Alabama,0.105513,1.260110,1.902348,data/NCAA_D1/assests/graphs/plot_3.png
4,U of South Carolina - college,"[[-81.0428983, 33.9859967], [-81.0433355, 33.9...","[[-81.0428983, 33.9859967], [-81.0419112, 33.9...",None,"[-81.0428983, 33.9859967]",23135.578200,101712.273767,124847.851966,0.185310,4.396358,...,33°59′12″N 81°2′38″W,Natural Bermuda Turf,The baseball stadium at the University of Sout...,53.107891,Columbia,South Carolina,-0.554716,2.136350,1.369808,data/NCAA_D1/assests/graphs/plot_4.png

In [203]:
len(teams)

64

In [204]:
import pandas as pd
import googlemaps

# Replace with your actual Google Maps API key
gmaps = googlemaps.Client(key='AIzaSyA_BhlTupRdBPBhRptQuR6pYorMVYQnRMA')

colleges = teams

# Initialize empty list to store results
results = []

for college in colleges:
    # Adjust the query to include 'baseball stadium'
    geocode_result = gmaps.geocode(f'{college} address')
    
    if geocode_result:
        # Extract the formatted address from the result
        address = geocode_result[0]['formatted_address']

        results.append({
            'College': college,
            'Baseball Stadium Address': address
        })
        ## If there is no result try a different search phrase
    else:
        address = gmaps.geocode(f'{college} baseball team')

        results.append({
            'College': college,
            'Baseball Stadium Address': address
        })
        


# ## List the teams that did not return a result
#     else:
#         print(f'No result for {college}')

# Convert results to DataFrame
address_df = pd.DataFrame(results)

In [205]:
address_df.info()
# df.info()

# len(teams)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 2 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   College                   64 non-null     object
 1   Baseball Stadium Address  64 non-null     object
dtypes: object(2)
memory usage: 1.1+ KB

In [206]:
## Take the values from the address_df and find it in the Team_Name column of the df dataframe
## Lookup the Host of for each team and add it to the address_df dataframe

address_df['Host'] = address_df['College'].map(df.set_index('Team_Name')['Host'])

address_df.head()

## Match Host to host_school in the host_df dataframe and grab the home_plate coordinates
address_df['End_point'] = address_df['Host'].map(host_df.set_index('host_school')['home_plate'])


# Rename Baseball Stadium Address to Visiting Team Address

address_df.rename(columns={'Baseball Stadium Address': 'Origin'}, inplace=True)

## If the team is the host drop the row
address_df = address_df[address_df['College'] != address_df['Host']]

In [207]:
address_df.head(20)

address_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 48 entries, 0 to 63
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   College    48 non-null     object
 1   Origin     48 non-null     object
 2   Host       48 non-null     object
 3   End_point  48 non-null     object
dtypes: object(4)
memory usage: 1.9+ KB

In [208]:
## Output csv to manually add the team colors
# address_df.to_csv('data/NCAA_D1/Routes_NO_COLOR_TEMP.csv')

## Reload the csv with the team colors
address_df = pd.read_csv('data/NCAA_D1/Routes_TEMP.csv')

In [209]:
address_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   College    48 non-null     object
 1   Origin     48 non-null     object
 2   Host       48 non-null     object
 3   End_point  48 non-null     object
 4   color1     48 non-null     object
 5   color2     48 non-null     object
dtypes: object(6)
memory usage: 2.4+ KB

In [210]:
## get all color info in hex codes

## make sure color1 and color2 are all lower case
address_df['color1'] = address_df['color1'].str.lower()
address_df['color2'] = address_df['color2'].str.lower()

df = address_df

import pandas as pd
import webcolors

def convert_to_hex(color):
    # Remove leading '#'
    if color.startswith('#'):
        color = color[1:]
    # Try to convert color names to hex
    try:
        return webcolors.name_to_hex(color).upper()
    # If color is already hex code
    except ValueError:
        if len(color) == 6:
            try:
                int(color, 16)  # check if hex color code is valid
                return '#' + color.upper()
            except ValueError:
                pass
    return None

# Assuming df is your dataframe and 'color1' is the name of the column
df['color1'] = df['color1'].apply(convert_to_hex)
df['color2'] = df['color2'].apply(convert_to_hex)

In [211]:
df.head()
df.info()

## SHow the teams that did not return a color
df[df['color2'].isnull()]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   College    48 non-null     object
 1   Origin     48 non-null     object
 2   Host       48 non-null     object
 3   End_point  48 non-null     object
 4   color1     48 non-null     object
 5   color2     48 non-null     object
dtypes: object(6)
memory usage: 2.4+ KB

Empty DataFrame
Columns: [College, Origin, Host, End_point, color1, color2]
Index: []

In [212]:
## Use google maps api to create lines (representing the quickest driving route) in the team colors from the visiting team to the host team

import googlemaps
from datetime import datetime

# Replace with your actual Google Maps API key
gmaps = googlemaps.Client(key='AIzaSyA_BhlTupRdBPBhRptQuR6pYorMVYQnRMA')

# Create a list of the polylines for each team
polylines = []

for i in range(len(df)):
    # Request directions via car
    now = datetime.now()
    origin = df['Origin'][i]
    end_point = df['End_point'][i]

    # If end_point is geographic coordinates in string format (lng, lat), convert it to tuple
    if isinstance(end_point, str) and ',' in end_point:
        # Strip brackets and spaces
        end_point = end_point.strip("[] ").split(',')
        # Swap latitude and longitude and convert to float
        end_point = (float(end_point[1]), float(end_point[0]))

    try:
        directions_result = gmaps.directions(origin, end_point, mode="driving", departure_time=now)
        polylines.append(directions_result[0]['legs'][0]['steps'][0]['polyline']['points'])
    except Exception as e:
        print(f"Failed to get directions for Origin: {origin}, End_point: {end_point}. Error: {e}")
        polylines.append(None)  # Add a None value if error occurs

## Add the polylines to the dataframe
df['polyline'] = polylines

df.head()

,College,Origin,Host,End_point,color1,color2,polyline
0,Southern Miss.,"118 College Dr, Hattiesburg, MS 39406, USA",Auburn,"[-85.4899848, 32.6000522]",#000000,#FFD700,s{e~Dvbf`PiB@gD@
1,Samford,"800 Lakeshore Dr, Homewood, AL 35229, USA",Auburn,"[-85.4899848, 32.6000522]",#000080,#FF0000,{zfkEryvpO@?LIVMXORM
2,Penn,"3331 River Fields Dr, Philadelphia, PA 08105, USA",Auburn,"[-85.4899848, 32.6000522]",#FF0000,#0000FF,k}xrFxy|iMTZlA`B`@j@X^j@v@DHJHDDDBB?B?B?F?D?DA...
3,Tulane,"6823 St Charles Ave, New Orleans, LA 70118, USA",LSU,"[-91.1877972, 30.4061259]",#006747,#43B02A,evuuDxbaePADCHCFCJCHAF?HAJAH?H?B?D?F@H@J?B@DBH...
4,Oregon St.,"430 Southwest Langton Place, Corvallis, OR 97331",LSU,"[-91.1877972, 30.4061259]",#FFA500,#000000,ey~nGpsloVBy@?]@M@K@M@Q@O?G@I?I?wA?gA

In [213]:
# ### apply the colors to the lines
# ## color 1 as base color, color2 a accent/border color
# ## if color2 is null then color1 is used for both

# ## create a list of colors for each line
# colors = []

# for i in range(len(df)):
#     if df['color2'][i] is None:
#         colors.append(df['color1'][i])
#     else:
#         colors.append(df['color1'][i] + ', ' + df['color2'][i])

# ## add the colors to the dataframe
# df['colors'] = colors

df.head()

,College,Origin,Host,End_point,color1,color2,polyline
0,Southern Miss.,"118 College Dr, Hattiesburg, MS 39406, USA",Auburn,"[-85.4899848, 32.6000522]",#000000,#FFD700,s{e~Dvbf`PiB@gD@
1,Samford,"800 Lakeshore Dr, Homewood, AL 35229, USA",Auburn,"[-85.4899848, 32.6000522]",#000080,#FF0000,{zfkEryvpO@?LIVMXORM
2,Penn,"3331 River Fields Dr, Philadelphia, PA 08105, USA",Auburn,"[-85.4899848, 32.6000522]",#FF0000,#0000FF,k}xrFxy|iMTZlA`B`@j@X^j@v@DHJHDDDBB?B?B?F?D?DA...
3,Tulane,"6823 St Charles Ave, New Orleans, LA 70118, USA",LSU,"[-91.1877972, 30.4061259]",#006747,#43B02A,evuuDxbaePADCHCFCJCHAF?HAJAH?H?B?D?F@H@J?B@DBH...
4,Oregon St.,"430 Southwest Langton Place, Corvallis, OR 97331",LSU,"[-91.1877972, 30.4061259]",#FFA500,#000000,ey~nGpsloVBy@?]@M@K@M@Q@O?G@I?I?wA?gA

In [214]:
## Reverse the order of the coordinates in the End_point column aned save it as a tuple
df['End_point'] = df['End_point'].apply(lambda x: tuple(reversed(eval(x))))

In [215]:
df.head()

,College,Origin,Host,End_point,color1,color2,polyline
0,Southern Miss.,"118 College Dr, Hattiesburg, MS 39406, USA",Auburn,"(32.6000522, -85.4899848)",#000000,#FFD700,s{e~Dvbf`PiB@gD@
1,Samford,"800 Lakeshore Dr, Homewood, AL 35229, USA",Auburn,"(32.6000522, -85.4899848)",#000080,#FF0000,{zfkEryvpO@?LIVMXORM
2,Penn,"3331 River Fields Dr, Philadelphia, PA 08105, USA",Auburn,"(32.6000522, -85.4899848)",#FF0000,#0000FF,k}xrFxy|iMTZlA`B`@j@X^j@v@DHJHDDDBB?B?B?F?D?DA...
3,Tulane,"6823 St Charles Ave, New Orleans, LA 70118, USA",LSU,"(30.4061259, -91.1877972)",#006747,#43B02A,evuuDxbaePADCHCFCJCHAF?HAJAH?H?B?D?F@H@J?B@DBH...
4,Oregon St.,"430 Southwest Langton Place, Corvallis, OR 97331",LSU,"(30.4061259, -91.1877972)",#FFA500,#000000,ey~nGpsloVBy@?]@M@K@M@Q@O?G@I?I?wA?gA

In [216]:
import gmaps
from geopy.geocoders import Nominatim

# Define your API Key (replace with your actual API Key)
gmaps.configure(api_key='AIzaSyA_BhlTupRdBPBhRptQuR6pYorMVYQnRMA')

# Instantiate the geocoder
geolocator = Nominatim(user_agent="myGeocoder")

## Draw the map
fig = gmaps.figure()

## iterate over rows
for i, row in df.iterrows():
    # Geocode the origin
    location = geolocator.geocode(row['Origin'])
    if location is not None:
        start_point = (location.latitude, location.longitude)
        end_point = row['End_point']
        # Create the drawing layer
        drawing1 = gmaps.drawing_layer(
            features=[gmaps.Line(start=start_point, end=end_point, stroke_weight=3.0, stroke_color=row['color1'])]
        )
        

        ## Create another drawing layer with wider lines to create a border effect
        drawing2 = gmaps.drawing_layer(
            features=[gmaps.Line(start=start_point, end=end_point, stroke_weight=5.0, stroke_color=row['color2'])]
        )

        # Add the drawing2 layer to the map
        fig.add_layer(drawing2)
        # Add the drawing1 layer to the map
        fig.add_layer(drawing1)

        # Create the marker layer
        marker_layer = gmaps.marker_layer([end_point], info_box_content=[f"{row['College']} at {row['Host']}"])
        # Add the marker layer to the map
        # fig.add_layer(marker_layer)

        
        



fig


## Open the fig in an external browser

Figure(layout=FigureLayout(height='420px'))

In [217]:
fig.open_in_browser()

AttributeError: 'Figure' object has no attribute 'open_in_browser'

In [ ]:
# from IPython.display import display
# import gmaps
# from gmaps import embed_minimal_html

# # Your existing code to create 'fig' goes here

# # To save as HTML:
# embed_minimal_html('TEMP/export.html', views=[fig])

ImportError: cannot import name 'embed_minimal_html' from 'gmaps' (c:\Users\Justin\anaconda3\lib\site-packages\gmaps\__init__.py)