In [1]:
### Clean up the conference data from the file that I manually checked

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Read in the data
df = pd.read_csv('TEMP/temp_cleaned_conference.csv')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 501 entries, 0 to 500
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   School      500 non-null    object
 1   conference  501 non-null    object
dtypes: object(2)
memory usage: 8.0+ KB

In [2]:
### drop rows that have duplicates in the school name

df.drop_duplicates(subset='School', keep='first', inplace=True)

df.info()

## replace any instances of the words 'High School' with 'HS'

df['School'] = df['School'].str.replace('High School', '')

## Remove any numbers from the school name

df['School'] = df['School'].str.replace('\d+', '')

# remove and brackets from the school name

df['School'] = df['School'].str.replace('[', '')
df['School'] = df['School'].str.replace(']', '')

# # Drop any rows that contain the word 'Toledo'

# df = df[~df['School'].str.contains('Toledo')]

### Add HS to the end of the school name

df['School'] = df['School'] + ' HS'










df.head(50)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 353 entries, 0 to 473
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   School      352 non-null    object
 1   conference  353 non-null    object
dtypes: object(2)
memory usage: 8.3+ KB

C:\Users\Justin\AppData\Local\Temp\ipykernel_9872\2357942382.py:13: FutureWarning: The default value of regex will change from True to False in a future version.
  df['School'] = df['School'].str.replace('\d+', '')
C:\Users\Justin\AppData\Local\Temp\ipykernel_9872\2357942382.py:17: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['School'] = df['School'].str.replace('[', '')
C:\Users\Justin\AppData\Local\Temp\ipykernel_9872\2357942382.py:18: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['School'] = df['School'].str.replace(']', '')

,School,conference
0,Alpena HS,Big North Conference
1,Cadillac HS,Big North Conference
2,Gaylord HS,Big North Conference
3,Petoskey HS,Big North Conference
4,Traverse City Central HS,Big North Conference
5,Traverse City West Senior HS,Big North Conference
6,DeWitt HS,Capital Area Activities Conference
7,East Lansing HS,Capital Area Activities Conference
8,Grand Ledge HS,Capital Area Activities Conference
9,Holt HS,Capital Area Activities Conference
10,Lansing Everett HS,Capital Area Activities Conference
11,Lansing Waverly HS,Capital Area Activities Conference
12,Okemos HS,Capital Area Activities Conference
13,Fowlerville HS,Capital Area Activities Conference
14,Haslett HS,Capital Area Activities Conference
15,Lansing Eastern HS,Capital Area Activities Conference
16,Mason HS,Capital Area Activities Conference
17,St. Johns HS,Capital Area Activities Conference
18,Williamston HS,Capital Area Activities Conference
19,Charlotte HS,Capital Area Activities Conference
20,Eaton Rapids HS,Capital Area Activities Conference
21,Ionia HS,Capital Area Activities Conference
22,Lansing Catholic HS,Capital Area Activities Conference
23,Lansing Sexton HS,Capital Area Activities Conference
24,Portland HS,Capital Area Activities Conference
25,Allen Park Cabrini HS,Catholic High School League
26,Ann Arbor Father Gabriel Richard HS,Catholic High School League
27,Ann Arbor Greenhills HS,Catholic High School League
28,Bloomfield Hills Brother Rice HS,Catholic High School League
29,Bloomfield Hills Academy of the Sacred Heart HS,Catholic High School League
30,Bloomfield Hills Cranbrook-Kingswood HS,Catholic High School League
31,Bloomfield Hills Marian HS,Catholic High School League
32,Clarkston Everest Collegiate HS,Catholic High School League
33,Dearborn Divine Child HS,Catholic High School League
34,Detroit Catholic Central HS,Catholic High School League
35,Detroit Cristo Rey HS,Catholic High School League
36,Detroit Loyola HS,Catholic High School League
37,University of Detroit Jesuit HS,Catholic High School League
38,Farmington Hills Mercy HS,Catholic High School League
39,Grosse Pointe Woods University Liggett HS,Catholic High School League
40,Macomb Austin Catholic HS,Catholic High School League
41,Macomb Lutheran North HS,Catholic High School League
42,Madison Heights Bishop Foley Catholic HS,Catholic High School League
43,Marine City Cardinal Mooney Catholic HS,Catholic High School League
44,Orchard Lake St. Mary's Preparatory HS,Catholic High School League
45,Riverview Gabriel Richard HS,Catholic High School League
46,Royal Oak Shrine Catholic HS,Catholic High School League
47,Toledo Central Catholic HS,Catholic High School League
48,Toledo Notre Dame Academy HS,Catholic High School League
49,Toledo St. Francis de Sales HS,Catholic High School League

In [3]:
df.info()

## Convert the school and conference names to strings

df['School'] = df['School'].astype(str)
df['conference'] = df['conference'].astype(str)

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 353 entries, 0 to 473
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   School      352 non-null    object
 1   conference  353 non-null    object
dtypes: object(2)
memory usage: 8.3+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 353 entries, 0 to 473
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   School      353 non-null    object
 1   conference  353 non-null    object
dtypes: object(2)
memory usage: 8.3+ KB

In [4]:
### Match the school name to the school name in the other data set and pull the school ID

# Read in the data

df2 = pd.read_csv('data/tables/mhsaa_enrolment_2022.csv')

df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 746 entries, 0 to 745
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   school_id    746 non-null    int64
 1   school_name  746 non-null    object
 2   students     746 non-null    int64
 3   enrollment   746 non-null    int64
 4   division     746 non-null    object
dtypes: int64(3), object(2)
memory usage: 29.3+ KB

In [5]:
### Match the school name to the school name in the other data set and pull the school ID

# Read in the data

df2 = pd.read_csv('data/tables/mhsaa_enrolment_2022.csv')

## Import dependencies

import pandas as pd
import numpy as np
from fuzzywuzzy import fuzz
from fuzzywuzzy import process

hs_names = df['School'].tolist()
mhsaa_names = df2['school_name'].tolist()

# set the treshold for the fuzzy match
treshold = 90
mat1 = []


## do the fuzzy match
for i in hs_names:
    mat1.append(process.extract(i, mhsaa_names, limit=1, scorer=fuzz.token_set_ratio))

df['match'] = mat1


### Take the first item in the tuple
df['match'] = df['match'].apply(lambda x: x[0][0])

#### Lookup the hs_df['match'] in the mhsaa_df['school_name'] and return the school_id
df['school_id'] = df['match'].apply(lambda x: df2[df2['school_name'] == x]['school_id'].values[0])

In [6]:
df.head()

## DID NOT CHECK MACHES BEFORE OUTPUTTING FILE
## Drop the match column
df.drop(columns=['match'], inplace=True)

## Output the file
df.to_csv('data/tables/mhsaa_conference.csv', index=False)